# Generated by Django 5.2.6 on 2025-10-19 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'verbose_name': 'CEP',
                'verbose_name_plural': 'CEPs',
                'db_table': 'cep',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoLogradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Logradouro',
                'verbose_name_plural': 'Tipos de Logradouro',
                'db_table': 'tipo_logradouro',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidade',
                'ordering': ['nome'],
                'unique_together': {('nome', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cidade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.tipologradouro')),
            ],
            options={
                'verbose_name': 'Logradouro',
                'verbose_name_plural': 'Logradouros',
                'db_table': 'logradouro',
                'ordering': ['nome'],
                'unique_together': {('nome', 'cidade', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cep')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.estado')),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.logradouro')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'endereco',
                'ordering': ['cidade', 'logradouro', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='cep',
            name='logradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.logradouro'),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=30, null=True, verbose_name='RG')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoa',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PessoaEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.endereco')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
            ],
            options={
                'verbose_name': 'Histórico de Endereço',
                'verbose_name_plural': 'Históricos de Endereço',
                'db_table': 'pessoa_endereco',
                'ordering': ['-data_inicio'],
                'unique_together': {('pessoa', 'endereco')},
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='enderecos',
            field=models.ManyToManyField(related_name='pessoas', through='accounts.PessoaEndereco', to='accounts.endereco'),
        ),
    ]
